### ISSUE TITLE
Changing equalArray method to equals

### ISSUE THREAD

**Issue by rohitppathak** [alexey-petrusevich/CS_4500_A1_part2#6]
Since all the Arrays override Object, we feel like they should just override equals and take in another Object. The current equalArray method takes in an Object* or int* or float*, etc., but this depends on an individual implementation (for us, we are not storing the an IntArray with a int*). Overriding equals would make everything standard.

**Comment by alexey-petrusevich** [comment]
The reason equals() and equalArray() are separated because equals() accepts another Array object and compares it to this Array. equalArray() accepts another block of ints, bools, and other types and compares it to this collection. Thus, you might have greater flexibility. Do you still need to have it removed?

**Comment by rohitppathak** [comment]
We personally won't be able to support it with those types because we are using composition to implement the primitive-type arrays, and so we aren't using blocks of ints, bools, and floats. If you could either support `equals(Object*)` or `equalArray(IntArray, or BoolArray, etc)`, we would appreciate it

**Comment by alexey-petrusevich** [comment]
The best I can do is to simply remove the method. If I change functionality, the implementation of other teams may be at risk. I'll remove the function.

**Comment by alexey-petrusevich** [comment]
Removed.
